-- T_ITEM_APP
INSERT INTO "T_ITEM_APP" ("ID", "CODE", "LABEL", "VALUE", "RANK", "ACTIVE", "START_DATE", "AUDIT_TIME") VALUES (S_ITEM_ID.NEXTVAL, 'ITEM_1', 'Item 1',  1.01, null, 1, to_date('2017-01-01', 'YYYY-MM-DD'), sysdate);
INSERT INTO "T_ITEM_APP" ("ID", "CODE", "LABEL", "VALUE", "RANK", "ACTIVE", "START_DATE", "AUDIT_TIME") VALUES (S_ITEM_ID.NEXTVAL, 'ITEM_2', 'Item 2',  2.02, null, 1, to_date('2017-01-01', 'YYYY-MM-DD'), sysdate);
INSERT INTO "T_ITEM_APP" ("ID", "CODE", "LABEL", "VALUE", "RANK", "ACTIVE", "START_DATE", "AUDIT_TIME") VALUES (S_ITEM_ID.NEXTVAL, 'ITEM_3', 'Item 3',  3.03, null, 0, to_date('2017-01-01', 'YYYY-MM-DD'), sysdate);


COMMIT;
